import type { NBProperty } from './nosBiensShared';

/**
 * Portefeuille de Mickaël Lima: fiches et photos récupérées le 10/08/2026
 * depuis les annonces publiées par L'agence Immo (lagenceimmo01.fr).
 * Photos servies depuis /public/images/biens/<réf>/.
 */
export const BIENS: NBProperty[] = [
  {
    ref: 'VM976',
    slug: 'maison-individuelle-5-pieces-grilly-01220-vm976',
    title: 'Maison Contemporaine 4 Suites Vue Panoramique Léman & Mont-Blanc Piscine Terrasse Jardin Double Garage Grilly 01220',
    type: 'Maison',
    typeLabel: 'Maison Individuelle',
    status: 'À vendre',
    city: 'Grilly',
    cp: '01220',
    price: 1800000,
    surface: 195,
    land: 1000,
    rooms: 5,
    bedrooms: 4,
    baths: 4,
    dpe: 'A',
    ges: 'A',
    coupDeCoeur: true,
    highlights: ['Performances énergétiques très bonnes', 'Idéalement exposé', 'Construction récente', 'Prestations et équipements de qualité', 'Salle d\'eau et wc dans chaque suite'],
    description: 'Mickaël Lima, spécialiste immobilier du Pays de Gex et de ses alentours, est ravi de vous présenter cette superbe maison individuelle contemporaine de 4 suites, alliant luminosité exceptionnelle, vue panoramique imprenable sur le Léman et le Mont-Blanc, et prestations haut de gamme, dans un environnement privilégié à Grilly.\n\nDès les premiers instants, cette propriété séduit par ses volumes baignés de lumière et son ouverture sur un paysage à couper le souffle, offrant un cadre de vie rare et recherché.\n\nAménagement intérieur :\n\nDès l’entrée, vous découvrez un espace accueillant et fonctionnel comprenant un WC indépendant ainsi qu’un bureau, idéal pour le télétravail ou une activité indépendante. Cet espace d’accueil introduit parfaitement la qualité de distribution de la maison.\n\nLa visite se poursuit vers une pièce de vie particulièrement spacieuse, baignée de lumière grâce à de larges ouvertures, et offrant une connexion naturelle avec l’extérieur ainsi qu’une vue panoramique exceptionnelle. La cuisine indépendante, entièrement aménagée et équipée, complète cet espace de vie avec élégance et praticité, permettant un usage aussi bien quotidien que convivial.\n\nLa maison se distingue par ses quatre véritables suites, chacune disposant de sa propre salle d’eau et de WC, garantissant un confort de vie optimal et une parfaite indépendance pour chaque occupant.\n\nLe chauffage au sol assure une chaleur douce et homogène dans toute la maison.\n\nUn sous-sol complète l’ensemble avec des espaces supplémentaires appréciables, ainsi qu’un garage permettant d’accueillir deux véhicules en toute sécurité.\n\nAménagement extérieur :\n\nImplantée sur un terrain d’environ 1 000 m², la propriété offre un cadre extérieur exceptionnel, véritable prolongement des espaces de vie. La terrasse d’environ 88 m², idéalement orientée, vous permet de profiter pleinement d’un panorama remarquable avec une vue dégagée sur le lac Léman et le Mont-Blanc, offrant un spectacle naturel unique au fil des saisons.\n\nLe jardin, soigneusement aménagé, constitue un espace de détente privilégié dans un environnement calme et verdoyant. La piscine, réalisée par Mondial Piscine, vient parfaire cet ensemble et offre un confort supplémentaire durant la belle saison, tout en s’intégrant harmonieusement dans ce cadre unique.\n\nLa propriété dispose également d’un garage pouvant accueillir deux véhicules, ainsi que de plusieurs places de stationnement extérieures permettant de garer au moins deux voitures supplémentaires.\n\nPrestations et équipements :\n\nCette maison récente bénéficie d’un niveau de prestations particulièrement qualitatif. Elle est équipée de stores BSO permettant de moduler finement la luminosité tout en conservant un excellent confort thermique. Un adoucisseur d’eau est également installé, améliorant le confort d’usage au quotidien.\n\nLa ventilation par VMC double flux assure un renouvellement constant de l’air tout en limitant les déperditions de chaleur, contribuant ainsi à un meilleur confort intérieur et à une optimisation énergétique. L’isolation par l’extérieur renforce les performances thermiques de la maison.\n\nLes menuiseries en aluminium avec double vitrage à isolation renforcée, intégrant du gaz argon, offrent une excellente performance thermique et acoustique tout en valorisant l’esthétique contemporaine du bien. L’ensemble est complété par des équipements modernes tels que la fibre optique et un système de visiophone.\n\nLocalisation et commodités :\n\nSituée à Grilly, dans un secteur recherché du Pays de Gex, à proximité immédiate de la douane de Sauverny, cette maison bénéficie d’un emplacement stratégique pour les frontaliers. Les commerces sont accessibles en quelques minutes en voiture, facilitant le quotidien. De nombreux sentiers de randonnée à proximité permettent de profiter pleinement d’un environnement naturel privilégié.\n\nInformations complémentaires :\n\nMaison disponible immédiatement, idéale pour un projet de résidence principale ou secondaire.',
    features: [
      ['Surface', '195 m²'],
      ['Pièces', '5'],
      ['Terrain', '1 000 m²'],
      ['Salle d\'eau', '4'],
      ['Niveaux (RDC inclus)', '2'],
      ['Chambres', '4'],
      ['WC', '5'],
      ['Piscine', 'Oui'],
      ['Stationnement intérieur', '2'],
      ['Stationnement extérieur', '2'],
      ['Cuisine', 'Aménagée et équipée/Indépendante'],
      ['Exposition', 'Sud-Est'],
      ['Jardin', 'Oui']
    ],
    photos: [
      '/images/biens/VM976/01.jpg',
      '/images/biens/VM976/02.jpg',
      '/images/biens/VM976/03.jpg',
      '/images/biens/VM976/04.jpg',
      '/images/biens/VM976/05.jpg',
      '/images/biens/VM976/06.jpg',
      '/images/biens/VM976/07.jpg',
      '/images/biens/VM976/08.jpg',
      '/images/biens/VM976/09.jpg',
      '/images/biens/VM976/10.jpg',
      '/images/biens/VM976/11.jpg',
      '/images/biens/VM976/12.jpg'
    ],
  },
  {
    ref: 'VM990',
    slug: 'maison-individuelle-7-pieces-sauverny-01220',
    title: 'Maison individuelle 5 chambres avec piscine, vue Mont-Blanc, jardin et garage à Sauverny (01220) : Proche frontière Suisse',
    type: 'Maison',
    typeLabel: 'Maison Individuelle',
    status: 'À vendre',
    city: 'Sauverny',
    cp: '01220',
    price: 1380000,
    surface: 196,
    land: 1440,
    rooms: 7,
    bedrooms: 5,
    baths: 3,
    dpe: 'C',
    ges: 'B',
    coupDeCoeur: true,
    highlights: ['Emplacement idéale', 'Équipements et isolation de la maison', 'Terrain entierement clôturé', 'Exposition idéale'],
    description: 'Mickaël Lima spécialiste immobilier du Pays de Gex et de ses alentours, est ravi de vous présenter cette maison individuelle de 5 chambres, offrant de beaux volumes, une vue imprenable sur le Mont-Blanc et un fort potentiel de valorisation, idéalement située à Sauverny.\n\nDès les premiers instants, cette propriété séduit par sa distribution fonctionnelle, ses espaces généreux et son environnement privilégié à proximité immédiate de la frontière suisse.\n\nAménagement intérieur :\n\nDès l’entrée, vous découvrez un espace d’accueil desservant harmonieusement les différentes pièces du rez-de-chaussée. La pièce de vie principale, lumineuse et conviviale, s’articule autour d’un séjour confortable agrémenté d’une cheminée, apportant chaleur et convivialité à cet espace de vie, prolongé par deux espaces salle à manger, offrant une configuration idéale pour recevoir et partager des moments en famille.\n\nLa cuisine indépendante, aménagée et équipée, apporte praticité et fonctionnalité au quotidien.\n\nCe niveau propose également une première chambre spacieuse avec dressing, ainsi qu’une seconde chambre, accompagnées de pièces d’eau. Chaque salle d’eau ainsi que la salle de bains disposent de leurs propres WC, garantissant un confort optimal au quotidien et une parfaite autonomie pour les occupants.\n\nÀ l’étage, l’espace nuit se développe avec trois chambres supplémentaires, dont une particulièrement agréable par ses volumes, ainsi que plusieurs espaces de rangement. Les différentes salles d’eau, également équipées de WC, assurent une organisation fluide et confortable pour toute la famille.\n\nLe sous-sol complète idéalement le bien avec des espaces annexes particulièrement appréciables, comprenant notamment une pièce pouvant faire office de chambre ou d’espace indépendant. Cet espace bénéficie de sa propre salle de douche avec WC, offrant une réelle autonomie et de nombreuses possibilités d’aménagement, que ce soit pour accueillir famille, amis ou pour un usage indépendant. Une buanderie, un atelier ainsi que des espaces techniques viennent compléter ce niveau. Un garage vient parfaire l’ensemble en offrant une solution de stationnement sécurisée.\n\nAménagement extérieur :\n\nLe jardin offre un cadre verdoyant et agréable, parfaitement adapté à la détente et aux moments de convivialité en extérieur. Entièrement clôturé par de hautes haies, le terrain permet de profiter des extérieurs en toute intimité, sans vis-à-vis, dans une atmosphère paisible et préservée.\n\nLa terrasse permet de savourer pleinement les beaux jours tout en admirant une vue dégagée exceptionnelle sur le Mont-Blanc, véritable atout rare dans le secteur.\n\nLa piscine constitue un véritable espace de détente durant la belle saison et s’intègre harmonieusement dans cet environnement extérieur soigné.\n\nUne place de stationnement extérieure vient compléter les prestations.\n\nPrestations et équipements :\n\nLa maison est équipée de radiateurs électriques, assurant un chauffage simple et efficace, ainsi que de menuiseries en double vitrage offrant un bon confort thermique et acoustique.\n\nUn système de panneaux solaires alimente la production d’eau chaude, représentant un véritable avantage en permettant de réduire la consommation énergétique et de mieux maîtriser les coûts sur le long terme, tout en s’inscrivant dans une démarche plus respectueuse de l’environnement.\n\nLa présence d’une cheminée dans le séjour constitue un véritable atout supplémentaire, apportant un confort chaleureux et une ambiance conviviale durant les périodes hivernales.\n\nLa ventilation assure un renouvellement efficace de l’air intérieur, contribuant à un cadre de vie sain et agréable.\n\nDes travaux de rafraîchissement permettront de révéler tout le potentiel de cette maison et de l’adapter pleinement à vos envies.\n\nLocalisation et commodités :\n\nSituée à Sauverny, à proximité immédiate de la douane, cette maison bénéficie d’un emplacement stratégique pour les frontaliers travaillant à Genève. Les axes de communication sont rapidement accessibles, facilitant les déplacements quotidiens.\n\nLes commerces, écoles et services se trouvent à quelques minutes, offrant un cadre de vie pratique et recherché. L’environnement naturel à proximité permet également de profiter pleinement des paysages du Pays de Gex.\n\nInformations complémentaires :\n\nMaison disponible immédiatement, idéale pour une famille à la recherche d’espace, de tranquillité et d’un emplacement privilégié à proximité de la Suisse.\n\nGrâce à une isolation performante et à des équipements tels que les panneaux solaires dédiés à la production d’eau chaude, la consommation énergétique actuelle du foyer reste particulièrement maîtrisée, avec un coût d’électricité d’environ 10 € par jour en période hivernale, ce qui représente un excellent niveau de performance pour une maison de cette surface.',
    features: [
      ['Surface', '196 m²'],
      ['Pièces', '7'],
      ['Salle de bains', '1'],
      ['Terrain', '1 440 m²'],
      ['Salle d\'eau', '2'],
      ['Séjour', '24 m²'],
      ['Niveaux (RDC inclus)', '2'],
      ['Chambres', '5'],
      ['WC', '3'],
      ['Piscine', 'Oui'],
      ['Stationnement intérieur', '1'],
      ['Stationnement extérieur', '1'],
      ['Cuisine', 'Aménagée et équipée/Indépendante']
    ],
    photos: [
      '/images/biens/VM990/01.jpg',
      '/images/biens/VM990/02.jpg',
      '/images/biens/VM990/03.jpg',
      '/images/biens/VM990/04.jpg',
      '/images/biens/VM990/05.jpg',
      '/images/biens/VM990/06.jpg',
      '/images/biens/VM990/07.jpg',
      '/images/biens/VM990/08.jpg',
      '/images/biens/VM990/09.jpg',
      '/images/biens/VM990/10.jpg',
      '/images/biens/VM990/11.jpg',
      '/images/biens/VM990/12.jpg'
    ],
  },
  {
    ref: 'VM1043',
    slug: 'maison-individuelle-5-pieces-grilly-01220-vm1043',
    title: 'Villa Neuve 185 M² : Vue Chaine des Alpes : 4 Chambres : Jardin & Terrasse : Garage : Grilly 01220',
    type: 'Maison',
    typeLabel: 'Maison Individuelle',
    status: 'À vendre',
    city: 'Grilly',
    cp: '01220',
    price: 1295000,
    surface: 185,
    land: 964,
    rooms: 5,
    bedrooms: 3,
    baths: 4,
    dpe: 'A',
    ges: 'A',
    coupDeCoeur: true,
    highlights: [],
    description: 'Mickaël Lima spécialiste immobilier, est ravi de vous présenter cette superbe villa contemporaine neuve, idéalement située dans un environnement recherché à Grilly. Développant 185 m² habitables, cette propriété séduit par ses volumes généreux, sa luminosité remarquable et sa vue panoramique exceptionnelle sur le Mont-Blanc et la chaîne des Alpes.\n\nAménagement intérieur :\n\nLe niveau principal accueille une superbe pièce de vie aux volumes généreux, baignée de lumière grâce à de larges ouvertures en aluminium offrant une continuité naturelle avec l’extérieur et une vue imprenable sur les reliefs alpins. Le séjour s’articule harmonieusement avec une cuisine américaine aménagée et équipée, créant un espace à la fois élégant et convivial, idéal pour recevoir, avec un accès direct à la terrasse et au jardin inférieur, prolongeant parfaitement les espaces de vie vers l’extérieur. Un WC indépendant complète ce niveau.\n\nLe rez-de-jardin inférieur, véritable espace nuit et détente, se compose d\'un grand dégagement qui vient structurer les circulations de ce niveau et offre un espace supplémentaire idéal pour un coin lecture, un espace détente ou un aménagement polyvalent. Il intègre également un véritable espace bureau de 22,38 m², parfaitement adapté au télétravail ou à une activité indépendante, constituant un atout rare et recherché.\n\nTrois chambres spacieuses, toutes équipées de placards intégrés et bénéficiant d’un accès direct au jardin inférieur, renforçant cette agréable sensation de dedans-dehors. La suite parentale se distingue par ses prestations complètes avec une salle de bains ainsi qu’une salle d’eau privative, constituant un véritable espace dédié au confort. Les autres chambres disposent chacune de leur salle d’eau attenante, offrant à chaque occupant un haut niveau d’intimité et de confort. Un second WC indépendant est également présent à ce niveau.\n\nAménagement extérieur :\n\nImplantée sur une parcelle de 964 m², la propriété bénéficie d’un environnement calme et privilégié. La terrasse prolonge naturellement les espaces de vie et offre un point de vue exceptionnel sur le Mont-Blanc et la chaîne des Alpes.\n\nLe jardin, exposé plein sud, constitue un véritable écrin de verdure, baigné de lumière et parfaitement aménageable selon vos envies, dans un cadre naturel rare. Il accueille également un espace spa, invitant à la détente et au bien-être, pour profiter pleinement des extérieurs en toute saison.\n\nUn abri voiture de 24 m², une cave de 5 m² ainsi que deux places de stationnements viennent compléter ce bien.\n\nPrestations et équipements :\n\nCette villa se distingue par la qualité de ses finitions et le soin apporté aux détails. Le carrelage grand format 1,20 m x 1,20 m apporte une touche résolument contemporaine et renforce la sensation d’espace dans les pièces de vie. Les menuiseries en aluminium, associées à de larges baies vitrées, offrent à la fois esthétisme, durabilité et excellente performance thermique. Les brise-soleil orientables motorisés (BSO) permettent une gestion optimale de la luminosité et du confort intérieur. L’ensemble de la robinetterie de la maison est signé Hansgrohe, gage de qualité, de durabilité et de design. Le chauffage au sol assure une diffusion douce et homogène de la chaleur, garantissant un confort optimal en toute saison. À l’extérieur, un spa vient compléter les prestations bien-être de la propriété, offrant un espace de détente privilégié.\n\nLocalisation et commodités :\n\nSituée à Grilly, à proximité immédiate de Divonne-les-Bains et Gex, cette propriété bénéficie d’un emplacement stratégique entre nature et accessibilité. Les commerces, écoles et services sont accessibles en quelques minutes. Le centre de Divonne-les-Bains, ses restaurants ainsi que le Golf de Divonne-les-Bains se rejoignent en environ 5 minutes. Les amateurs de nature apprécieront l’accès immédiat au Mont Mourex. La frontière franco-suisse est accessible en quelques minutes, tandis que l’Aéroport international de Genève se situe à environ 20 minutes, facilitant tous vos déplacements.\n\nInformations complémentaires :\n\nMaison neuve disponible immédiatement, offrant une opportunité rare d’acquérir un bien moderne avec vue exceptionnelle dans un secteur très recherché. Pour davantage d’informations sur les risques éventuels, rendez-vous sur le site www.georisques.gouv.fr.',
    features: [
      ['Surface', '185 m²'],
      ['Pièces', '5'],
      ['Salle de bains', '1'],
      ['Terrain', '964 m²'],
      ['Salle d\'eau', '3'],
      ['Niveaux (RDC inclus)', '2'],
      ['Chambres', '3'],
      ['WC', '2'],
      ['Piscine', 'Non'],
      ['Stationnement intérieur', '1'],
      ['Stationnement extérieur', '2'],
      ['Cuisine', 'Aménagée et équipée/Américaine'],
      ['Exposition', 'Sud']
    ],
    photos: [
      '/images/biens/VM1043/01.jpg',
      '/images/biens/VM1043/02.jpg',
      '/images/biens/VM1043/03.jpg',
      '/images/biens/VM1043/04.jpg',
      '/images/biens/VM1043/05.jpg',
      '/images/biens/VM1043/06.jpg',
      '/images/biens/VM1043/07.jpg',
      '/images/biens/VM1043/08.jpg',
      '/images/biens/VM1043/09.jpg',
      '/images/biens/VM1043/10.jpg',
      '/images/biens/VM1043/11.jpg',
      '/images/biens/VM1043/12.jpg'
    ],
  },
  {
    ref: 'VM560',
    slug: 'maison-individuelle-8-pieces-crozet-01170',
    title: 'Maison de Standing à Crozet 01170 : 201 m², Vue Alpes & Prestations Haut de Gamme',
    type: 'Maison',
    typeLabel: 'Maison Individuelle',
    status: 'À vendre',
    city: 'Crozet',
    cp: '01170',
    price: 1030000,
    surface: 201.7,
    land: 712,
    rooms: 8,
    bedrooms: 5,
    baths: 3,
    dpe: 'B',
    ges: 'A',
    coupDeCoeur: false,
    highlights: ['système domotique KNX Hager', 'bonnes performances energetiques', 'prestations de standing', 'cinq chambres'],
    description: 'Mickaël Lima spécialiste immobilier sur le Pays de Gex et ses environs, a le plaisir de vous présenter une maison contemporaine de 201,70 m² habitables. Construite en 2015, elle offre des volumes généreux, une conception moderne et un confort de vie rare. Située sur une parcelle de 712 m², la propriété bénéficie d’une vue panoramique exceptionnelle sur la chaîne des Alpes.\n\nAménagement intérieur :\n\nAu rez-de-chaussée, un dégagement dessert une salle de jeux ainsi que deux chambres orientées vers les montagnes. Une salle d’eau avec WC complète ce niveau.\n\nAu rez-de-jardin, un vaste séjour baigné de lumière s’ouvre sur une cuisine sur mesure, réalisée par un artisan cuisiniste, et se prolonge par un salon indépendant. Ce niveau comprend également un WC indépendant, une buanderie aménagée, ainsi qu’un espace bien-être doté d’un sauna et d’un hammam.\n\nAu premier étage, deux suites parentales profitent d’une vue splendide sur les Alpes et disposent chacune d’un balcon privatif. La première suite dispose d’une salle de bains complète avec WC, douche et d’un dressing. La seconde offre une salle de douche avec WC et un balcon avec vue dégagée.\n\nAménagement extérieur :\n\nLe jardin de 712 m² s’accompagne d’une terrasse exposée Sud-Est, parfaite pour profiter de l’ensoleillement et du panorama montagnard. Un garage simple attenant et communicant avec la maison assure un accès direct. Cinq stationnements extérieurs viennent compléter les aménagements, offrant une solution pratique pour plusieurs véhicules.\n\nPrestations et équipements :\n\nLa maison dispose d’une isolation extérieure performante, de menuiseries aluminium double vitrage, ainsi que d’un système de chauffage et de rafraîchissement via une pompe à chaleur air-eau, distribué par un plancher chauffant couvrant l’ensemble des trois niveaux. Le rez-de-jardin est revêtu d’un carrelage en grès cérame porcelainato. Un système domotique KNX Hager permet une gestion centralisée du chauffage, de l’éclairage et des ouvrants. Le sauna et le hammam situés au rez-de-jardin complètent les équipements de confort.\n\nLocalisation et commodités :\n\nSituée à Crozet, la maison offre un cadre naturel privilégié, tout en étant à proximité immédiate du resort de loisirs Jiva Hill Resort: resort 5 étoiles avec spa, golf et activités de loisirs: ce qui constitue un avantage notable pour les détenteurs ou visiteurs.  À quelques minutes également : la station de ski Monts-Jura (site Crozet-Lélex), des restaurants, la zone commerciale de Saint-Genis-Pouilly, et un accès rapide à la suisse via la douane de Meyrin.\n\nInformations complémentaires :\n\nLe bien est libre immédiatement, ce qui permet une installation rapide ou la mise en place de votre projet sans délai. La maison offre de solides performances énergétiques, avec une consommation classée B et des émissions classées A, garantissant un confort appréciable au quotidien.\n\nVous profiterez également de prestations soignées et d’un agencement fonctionnel.',
    features: [
      ['Surface', '201.7 m²'],
      ['Pièces', '8'],
      ['Salle de bains', '1'],
      ['Terrain', '712 m²'],
      ['Salle d\'eau', '2'],
      ['Séjour', '42 m²'],
      ['Niveaux (RDC inclus)', '3'],
      ['Chambres', '5'],
      ['WC', '4'],
      ['Stationnement intérieur', '1'],
      ['Stationnement extérieur', '5'],
      ['Cuisine', 'Aménagée et équipée'],
      ['Exposition', 'Sud-Est'],
      ['Jardin', 'Oui']
    ],
    photos: [
      '/images/biens/VM560/01.jpg',
      '/images/biens/VM560/02.jpg',
      '/images/biens/VM560/03.jpg',
      '/images/biens/VM560/04.jpg',
      '/images/biens/VM560/05.jpg',
      '/images/biens/VM560/06.jpg',
      '/images/biens/VM560/07.jpg',
      '/images/biens/VM560/08.jpg',
      '/images/biens/VM560/09.jpg',
      '/images/biens/VM560/10.jpg',
      '/images/biens/VM560/11.jpg',
      '/images/biens/VM560/12.jpg'
    ],
  },
  {
    ref: 'VM1126',
    slug: 'maison-individuelle-5-pieces-divonne-les-bains-01220',
    title: 'Maison individuelle de 196 m² avec jardin, terrasse et appartement indépendant à Divonne-les-Bains 01220',
    type: 'Maison',
    typeLabel: 'Maison Individuelle',
    status: 'À vendre',
    city: 'Divonne-les-Bains',
    cp: '01220',
    price: 995000,
    surface: 196,
    land: 472,
    rooms: 5,
    bedrooms: 3,
    baths: 3,
    dpe: 'A',
    ges: 'A',
    coupDeCoeur: false,
    highlights: ['Prestations de qualité', 'Grandes ouvertures', 'Appartement indépendant', 'Stores BSO', 'Excellentes performances énergétiques'],
    description: 'Située à Arbère, hameau recherché de Divonne-les-Bains, cette maison profite d\'un environnement résidentiel calme tout en restant à proximité immédiate des commerces, des écoles, du lac de Divonne, du golf, des thermes et de l\'ensemble des commodités. Genève, Nyon et la frontière suisse sont rapidement accessibles, faisant de cette adresse un emplacement privilégié pour les travailleurs frontaliers comme pour les familles.\n\nInformations complémentaires :\n\nMaison hors copropriété. DPE : A (60 kWhEP/m².an) - GES : A (2 kg CO₂/m².an). Montant estimé des dépenses annuelles d\'énergie : entre 900 € et 1 280 € par an. Assainissement : tout-à-l\'égout conforme. Le bien est disponible immédiatement.',
    features: [
      ['Surface', '196 m²'],
      ['Pièces', '5'],
      ['Salle de bains', '3'],
      ['Terrain', '472 m²'],
      ['Séjour', '63 m²'],
      ['Niveaux (RDC inclus)', '3'],
      ['Chambres', '3'],
      ['WC', '3'],
      ['Piscine', 'Non'],
      ['Stationnement intérieur', '2'],
      ['Stationnement extérieur', '2'],
      ['Cuisine', 'Aménagée et équipée/Américaine'],
      ['Exposition', 'Sud-Est'],
      ['Jardin', 'Oui']
    ],
    photos: [
      '/images/biens/VM1126/01.jpg',
      '/images/biens/VM1126/02.jpg',
      '/images/biens/VM1126/03.jpg',
      '/images/biens/VM1126/04.jpg',
      '/images/biens/VM1126/05.jpg',
      '/images/biens/VM1126/06.jpg',
      '/images/biens/VM1126/07.jpg',
      '/images/biens/VM1126/08.jpg',
      '/images/biens/VM1126/09.jpg',
      '/images/biens/VM1126/10.jpg',
      '/images/biens/VM1126/11.jpg',
      '/images/biens/VM1126/12.jpg'
    ],
  },
  {
    ref: 'VM615',
    slug: 'maison-individuelle-5-pieces-peron-01630',
    title: 'Maison contemporaine 144 m² avec 3 suites, vue Alpes, terrasse et garage : Péron 01630',
    type: 'Maison',
    typeLabel: 'Maison Individuelle',
    status: 'À vendre',
    city: 'Péron',
    cp: '01630',
    price: 835000,
    surface: 143.74,
    land: 495,
    rooms: 5,
    bedrooms: 3,
    baths: 3,
    dpe: 'B',
    ges: 'A',
    coupDeCoeur: false,
    highlights: ['Maison bien entrenue', 'Rideaux sur mesure', 'Cuisine aménagée et équipée', '3 suites avec vue dégagée', 'Orientation idéale'],
    description: 'Mickaël Lima spécialiste immobilier est ravie de vous présenter cette maison individuelle contemporaine construite en 2018, offrant 144 m² habitables, idéalement située au pied du Jura dans un environnement naturel privilégié. Le bien bénéficie d’une vue exceptionnelle sur les Alpes, perceptible depuis l’ensemble des pièces de la maison, conférant un cadre de vie rare et apaisant.\n\nDéveloppée sur deux niveaux, cette propriété propose une organisation idéale avec trois véritables suites, chacune disposant de son espace dressing et de sa salle d’eau ou salle de bains, ainsi que des espaces de vie lumineux et parfaitement agencés.\n\nAménagement intérieur :\n\nDès l’entrée, la maison dévoile une atmosphère élégante portée par une décoration douce et apaisante, où chaque espace a été pensé pour offrir confort et sérénité au quotidien.\n\nLe hall distribue harmonieusement les différents espaces du rez-de-chaussée, comprenant un WC indépendant suspendu ainsi qu’un espace cellier/buanderie idéalement positionné dès l’entrée, apportant un véritable confort d’usage au quotidien.\n\nL’espace de vie se compose d’un séjour lumineux, prolongé par une salle à manger conviviale, le tout bénéficiant d’une vue imprenable sur les Alpes, comme dans chaque pièce de la maison. La cuisine aménagée et équipée, s’inscrit dans la continuité de cet espace avec un agencement fonctionnel.\n\nCe niveau accueille également une première suite avec dressing, salle d’eau et WC suspendu privatifs, offrant un confort de plain-pied particulièrement recherché.\n\nÀ l’étage, l’agencement a été pensé avec élégance et fluidité. Un espace ouvert de type mezzanine, aménagé dans le dégagement, constitue un véritable lieu de vie supplémentaire, idéal pour un espace bureau, un coin lecture ou un espace détente. Ce volume central distribue harmonieusement les deux suites de l’étage, tout en conservant une belle sensation d’ouverture et de luminosité.\n\nLes deux suites offrent des volumes agréables, l’une disposant d’une salle d’eau privative et l’autre d’une salle de bains. Chacune bénéficie également de son dressing, alliant confort et fonctionnalité.\n\nUn balcon filant, accessible depuis l’ensemble des pièces de l’étage, prolonge harmonieusement les espaces intérieurs et offre une vue dégagée sur les Alpes. Son garde-corps en verre renforce la sensation d’ouverture et de modernité.\n\nUn WC indépendant suspendu complète ce niveau.\n\nAménagement extérieur :\n\nLa maison profite d’un extérieur agréable et parfaitement équipé. Le jardin permet de savourer pleinement un environnement calme et verdoyant, tandis que la terrasse constitue un espace privilégié pour les moments de convivialité en extérieur.\n\nPlusieurs points d’eau ont été installés afin de faciliter l’arrosage, accompagnés de prises électriques extérieures pratiques pour les usages du quotidien.\n\nUn système d’éclairage par spots disposés tout autour de la maison permet de sublimer l’architecture du bien à la nuit tombée et de créer une ambiance élégante et chaleureuse.\n\nUn garage ainsi que plusieurs places de stationnement extérieures viennent compléter l’ensemble avec praticité.\n\nPrestations et équipements :\n\nCette maison récente bénéficie de prestations modernes et particulièrement soignées. Elle est dotée d’une isolation thermique par l’extérieur, garantissant un excellent confort en toute saison.\n\nLe système de chauffage repose sur une pompe à chaleur air/eau avec programmateur, alimentant un plancher chauffant sur l’ensemble de la maison pour une diffusion douce et homogène de la chaleur.\n\nLes menuiseries en aluminium associées à des volets roulants motorisés participent à la qualité globale du bien.\n\nLes suites disposent toutes de dressings aménagés, apportant un confort de rangement optimal.\n\nEnfin, un soin particulier a été apporté aux finitions avec des rideaux sur mesure intégrés sur des rails invisibles encastrés au plafond, offrant une signature esthétique contemporaine et épurée.\n\nL’ensemble des WC de la maison sont suspendus, renforçant le caractère moderne et qualitatif du bien.\n\nLocalisation et commodités :\n\nSituée à Péron, dans un cadre naturel recherché au pied du Jura, cette propriété bénéficie d’un environnement privilégié entre nature et accessibilité. Les amateurs de plein air apprécieront la proximité immédiate des sentiers de randonnée.\n\nLa commune dispose de toutes les commodités essentielles : commerces, services de santé et infrastructures du quotidien. Les établissements scolaires sont accessibles à proximité, avec une continuité vers les structures éducatives de Genève.\n\nLa proximité de la frontière suisse constitue un atout majeur pour les frontaliers.\n\nCôté transports, la ligne de bus 33 reliant Bellegarde-sur-Valserine à Divonne-les-Bains permet de rejoindre efficacement les axes principaux et les communes environnantes.\n\nInformations complémentaires :\n\nDPE : B (105 kWhEP/m².an) : GES : A (4 kg CO₂/m².an).\n\nMontant estimé des dépenses annuelles d’énergie : entre 1 410 € et 1 960 € par an.',
    features: [
      ['Surface', '143.74 m²'],
      ['Pièces', '5'],
      ['Salle de bains', '1'],
      ['Terrain', '495 m²'],
      ['Salle d\'eau', '2'],
      ['Niveaux (RDC inclus)', '2'],
      ['Chambres', '3'],
      ['WC', '3'],
      ['Piscine', 'Non'],
      ['Stationnement intérieur', '1'],
      ['Stationnement extérieur', '3'],
      ['Cuisine', 'Aménagée et équipée/Indépendante'],
      ['Exposition', 'Sud-Est']
    ],
    photos: [
      '/images/biens/VM615/01.jpg',
      '/images/biens/VM615/02.jpg',
      '/images/biens/VM615/03.jpg',
      '/images/biens/VM615/04.jpg',
      '/images/biens/VM615/05.jpg',
      '/images/biens/VM615/06.jpg',
      '/images/biens/VM615/07.jpg',
      '/images/biens/VM615/08.jpg',
      '/images/biens/VM615/09.jpg',
      '/images/biens/VM615/10.jpg',
      '/images/biens/VM615/11.jpg',
      '/images/biens/VM615/12.jpg'
    ],
  },
  {
    ref: 'VM1093',
    slug: 'maison-individuelle-6-pieces-collonges-01550',
    title: 'Maison De 172 m2 Avec Vue Montagne, Yourte De 50 M² Et Terrain De 1 674 M²',
    type: 'Maison',
    typeLabel: 'Maison Individuelle',
    status: 'À vendre',
    city: 'Collonges',
    cp: '01550',
    price: 820000,
    surface: 170.22,
    land: 1674,
    rooms: 6,
    bedrooms: 5,
    baths: 3,
    dpe: 'C',
    ges: 'A',
    coupDeCoeur: true,
    highlights: ['Emplacement idéale au calme', 'Aucun travaux à prévoir', 'Vue', 'Agencement de la maison'],
    description: 'Située à Collonges, dans un environnement calme et verdoyant, cette propriété bénéficie d\'un emplacement privilégié aux portes de la Suisse. Les commerces, écoles et services du quotidien sont facilement accessibles, tandis que la frontière suisse, Meyrin, le CERN et l\'aéroport international de Genève sont rapidement rejoignables. Les amateurs de nature apprécieront la proximité immédiate des sentiers de randonnée du Jura et du secteur du Fort l\'Écluse. Un cadre de vie idéal alliant tranquillité, vue sur les montagnes et proximité des principaux bassins d\'emploi de la région.\n\nInformations complémentaires :\n\nMontant estimé des dépenses annuelles d\'énergie pour un usage standard : entre 1 434 € et 1 940 € par an.\n\nDisponibilité : le bien est disponible immédiatement.',
    features: [
      ['Surface', '170.22 m²'],
      ['Pièces', '6'],
      ['Salle de bains', '1'],
      ['Terrain', '1 674 m²'],
      ['Salle d\'eau', '2'],
      ['Niveaux (RDC inclus)', '2'],
      ['Chambres', '5'],
      ['WC', '2'],
      ['Piscine', 'Non'],
      ['Stationnement intérieur', '1'],
      ['Stationnement extérieur', '5'],
      ['Cuisine', 'Aménagée et équipée/Américaine'],
      ['Jardin', 'Oui']
    ],
    photos: [
      '/images/biens/VM1093/01.jpg',
      '/images/biens/VM1093/02.jpg',
      '/images/biens/VM1093/03.jpg',
      '/images/biens/VM1093/04.jpg',
      '/images/biens/VM1093/05.jpg',
      '/images/biens/VM1093/06.jpg',
      '/images/biens/VM1093/07.jpg',
      '/images/biens/VM1093/08.jpg',
      '/images/biens/VM1093/09.jpg',
      '/images/biens/VM1093/10.jpg',
      '/images/biens/VM1093/11.jpg',
      '/images/biens/VM1093/12.jpg'
    ],
  },
  {
    ref: 'VM920',
    slug: 'maison-individuelle-5-pieces-echenevex-01170',
    title: 'Maison individuelle 168 m² : Terrasse 88 m² : Vue Jura : 3 chambres : Échenevex 01170',
    type: 'Maison',
    typeLabel: 'Maison Individuelle',
    status: 'À vendre',
    city: 'Échenevex',
    cp: '01170',
    price: 795000,
    surface: 168,
    land: 969,
    rooms: 5,
    bedrooms: 3,
    baths: 2,
    dpe: 'C',
    ges: 'B',
    coupDeCoeur: false,
    highlights: ['Maison très bien entretenue', 'Vue dégagée', 'Terrain bien entretenu', 'Nombreuses places de stationnement', 'Exposition idéale'],
    description: 'Mickaël Lima spécialiste immobilier sur le secteur du Pays de Gex et alentours, est ravi de vous présenter cette maison individuelle située à Échenevex, offrant un cadre de vie paisible et recherché à proximité immédiate de la frontière suisse. Il s’agit d’une maison de 168,35 m² utiles et 136,31 habitables  comprenant une pièce de vie avec cuisine ouverte, trois chambres dont une suite parentale, une salle de bains, une salle d’eau, trois WC dont un indépendant, ainsi qu’un garage et un agréable extérieur.\n\nAménagement intérieur :\n\nLa maison s’ouvre sur un espace de vie lumineux comprenant un séjour avec cuisine américaine aménagée et équipée, permettant une organisation fonctionnelle du quotidien. L’exposition sud-ouest apporte une belle luminosité tout au long de la journée.\n\nL’espace nuit se compose de trois chambres, dont une suite parentale avec sa salle d’eau privative, son WC et son dressing. Les deux chambres situées à l’étage bénéficient d’un dressing commun.\n\nUne mezzanine vient compléter l’ensemble, offrant un espace supplémentaire pouvant être aménagé selon vos besoins.\n\nUne salle de bains supplémentaire avec WC ainsi qu’un WC indépendant au rez-de-chaussée complètent le confort de la maison.\n\nLe garage est complété par une buanderie située dans son prolongement, offrant un espace fonctionnel et pratique au quotidien.\n\nAménagement extérieur :\n\nImplantée sur un terrain de 969 m², la propriété bénéficie d’un extérieur soigné et parfaitement entretenu. Dès l’entrée, une grande allée aménagée met en valeur l’accès à la maison.\n\nLe jardin offre un cadre agréable permettant de profiter pleinement des beaux jours.\n\nLa terrasse de 88 m², véritable prolongement de l’espace de vie, est idéale pour les repas en extérieur et les moments de détente.\n\nÀ l’arrière, l’environnement s’ouvre sur des champs à perte de vue. La maison bénéficie également d’une vue dégagée sur le massif du Jura.\n\nLe terrain est piscinable et plusieurs places de stationnement extérieures complètent l’ensemble.\n\nPrestations et équipements :\n\nLa maison bénéficie d’une bonne isolation générale et de menuiseries en double vitrage, assurant confort et performance énergétique. Le chauffage au sol, alimenté par une pompe à chaleur, garantit une diffusion homogène et agréable de la chaleur au rez-de-chaussée, tandis que l’étage est équipé de radiateurs. L’ensemble est complété par un poêle à bois apportant une touche chaleureuse supplémentaire.\n\nLe bien est également équipé d’un adoucisseur d’eau, de volets électriques, de la fibre optique ainsi que d’un système de ventilation mécanique, offrant un confort optimal au quotidien.\n\nLocalisation et commodités :\n\nSituée à Échenevex, dans un environnement calme, la maison reste proche des écoles, commerces et restaurants. Carrefour Market Gex et le Golf de Maison Blanche sont à environ 5 minutes. Accès direct aux sentiers du Jura. La frontière suisse (CERN, Meyrin) est accessible en une dizaine de minutes.\n\nInformations complémentaires :\n\nDPE : C (156 kWhEP/m².an) : GES : B (6 kg CO₂/m².an)\n\nEstimation énergie : entre 1 879 € et 2 543 € / an\n\nInformations sur les risques : www.georisques.gouv.fr',
    features: [
      ['Surface', '168 m²'],
      ['Pièces', '5'],
      ['Salle de bains', '1'],
      ['Terrain', '969 m²'],
      ['Salle d\'eau', '1'],
      ['Niveaux (RDC inclus)', '2'],
      ['Chambres', '3'],
      ['WC', '3'],
      ['Piscine', 'Non'],
      ['Stationnement intérieur', '1'],
      ['Stationnement extérieur', '3'],
      ['Cuisine', 'Aménagée et équipée/Américaine'],
      ['Exposition', 'Sud-Ouest'],
      ['Jardin', 'Oui']
    ],
    photos: [
      '/images/biens/VM920/01.jpg',
      '/images/biens/VM920/02.jpg',
      '/images/biens/VM920/03.jpg',
      '/images/biens/VM920/04.jpg',
      '/images/biens/VM920/05.jpg',
      '/images/biens/VM920/06.jpg',
      '/images/biens/VM920/07.jpg',
      '/images/biens/VM920/08.jpg',
      '/images/biens/VM920/09.jpg',
      '/images/biens/VM920/10.jpg',
      '/images/biens/VM920/11.jpg',
      '/images/biens/VM920/12.jpg'
    ],
  },
  {
    ref: 'VM1140',
    slug: 'maison-individuelle-5-pieces-villeneuve-les-maguelone-34750',
    title: 'Maison de plain-pied 130 m² - Terrain d\'1 hectare - Piscine - Villeneuve-lès-Maguelone (34750)',
    type: 'Maison',
    typeLabel: 'Maison Individuelle',
    status: 'À vendre',
    city: 'Villeneuve-lès-Maguelone',
    cp: '34750',
    price: 665000,
    surface: 130,
    land: 10000,
    rooms: 5,
    bedrooms: 4,
    baths: 2,
    dpe: 'B',
    ges: 'A',
    coupDeCoeur: false,
    highlights: ['Potentiel équestre', 'Aucun travaux à prévoir', 'Puit sur le terrain', 'Veranda chaufée', 'Endroit calme'],
    description: 'Mickaël Lima expert immobilier, vous présente cette maison individuelle de plain-pied entièrement rénovée en 2016. Implantée sur un terrain d\'un hectare, elle développe 130 m² habitables et offre un cadre de vie rare, alliant confort, modernité et grands espaces. Située à seulement 15 minutes de Montpellier et à 5 minutes des plages, cette propriété séduira aussi bien les familles que les amoureux de nature et d\'équitation.\n\nAménagement intérieur :\n\nDès l\'entrée, vous découvrirez un dégagement desservant une agréable pièce de vie où le séjour et la cuisine entièrement aménagée et équipée s\'harmonisent parfaitement pour offrir un espace convivial et lumineux. Dans son prolongement, une vaste véranda chauffée apporte une véritable pièce de vie supplémentaire, idéale pour profiter des extérieurs tout au long de l\'année. Un bureau indépendant complète cet espace, offrant un cadre idéal pour le télétravail ou une activité à domicile. La partie nuit se compose de trois chambres avec placards intégrés, dont une suite parentale avec sa salle d\'eau et son WC privatifs. Une seconde salle d\'eau ainsi qu\'un WC indépendant viennent compléter cet agencement fonctionnel pensé pour le confort de toute la famille.\n\nAménagement extérieur :\n\nÀ l\'extérieur, le charme opère immédiatement. Implantée sur une parcelle d\'un hectare, cette propriété offre un environnement privilégié où chacun pourra profiter pleinement des grands espaces. La terrasse invite à partager de beaux moments de convivialité aux beaux jours, tandis que la piscine hors sol complète agréablement les prestations. Les amateurs de chevaux apprécieront le potentiel du terrain, parfaitement adapté pour accueillir des équidés. Un garage ouvert permet d\'abriter deux véhicules, complété par de nombreuses possibilités de stationnement. Un puits vient également agrémenter la propriété et assure une alimentation en eau particulièrement appréciable pour l\'entretien des espaces extérieurs.\n\nEntièrement rénovée en 2016, la maison bénéficie de prestations offrant un excellent niveau de confort. Elle est équipée d\'une pompe à chaleur air/air avec climatisation gainable réversible, d\'un chauffe-eau électrique de 300 litres associé à un adoucisseur d\'eau, ainsi que d\'une isolation intérieure de 60 cm au niveau des combles. Les menuiseries PVC à double vitrage avec lame d\'argon garantissent une excellente performance thermique. Fibre optique, VMC simple flux, portail motorisé, store banne motorisé, ouvertures domotisées et système de vidéosurveillance viennent compléter les équipements de cette propriété.\n\nLocalisation et commodités :\n\nCette maison profite d\'un emplacement particulièrement recherché, offrant un parfait équilibre entre campagne et littoral. Montpellier est accessible en seulement quinze minutes, tandis que les plages, notamment la plage du Pilou, se rejoignent en cinq minutes. Commerces, écoles, services et principaux axes routiers sont rapidement accessibles, facilitant le quotidien. Ce secteur est particulièrement apprécié pour sa qualité de vie, son environnement préservé et son fort potentiel, offrant un cadre idéal pour les familles comme pour les amoureux de grands espaces.\n\nInformations complémentaires :\n\nAssainissement individuel par fosse septique conforme. Le bien est disponible immédiatement. DPE : B (93 kWhEP/m².an) - GES : A (3 kg CO₂/m².an). Montant estimé des dépenses annuelles d\'énergie : entre 850 € et 1 210 € par an (année de référence 2021). Les informations sur les risques auxquels ce bien est exposé sont disponibles sur le site Géorisques.\n\nUn bien rare offrant un cadre de vie privilégié aux portes de Montpellier et à quelques minutes seulement du littoral.\n\nL\'agence immo, plus qu\'une agence, une expérience.',
    features: [
      ['Surface', '130 m²'],
      ['Pièces', '5'],
      ['Terrain', '10 000 m²'],
      ['Salle d\'eau', '2'],
      ['Chambres', '4'],
      ['WC', '2'],
      ['Piscine', 'Oui'],
      ['Stationnement intérieur', '2'],
      ['Stationnement extérieur', '4'],
      ['Cuisine', 'Aménagée et équipée/Coin cuisine'],
      ['Exposition', 'Sud-Ouest']
    ],
    photos: [
      '/images/biens/VM1140/01.jpg',
      '/images/biens/VM1140/02.jpg',
      '/images/biens/VM1140/03.jpg',
      '/images/biens/VM1140/04.jpg',
      '/images/biens/VM1140/05.jpg',
      '/images/biens/VM1140/06.jpg',
      '/images/biens/VM1140/07.jpg',
      '/images/biens/VM1140/08.jpg',
      '/images/biens/VM1140/09.jpg',
      '/images/biens/VM1140/10.jpg',
      '/images/biens/VM1140/11.jpg',
      '/images/biens/VM1140/12.jpg'
    ],
  },
  {
    ref: 'VM1022',
    slug: 'maison-chalet-3-pieces-evian-les-bains-74500',
    title: 'Chalet 75 M² - Vue Lac Léman - Fort Potentiel Constructible - Terrain - Évian-les-Bains 74500',
    type: 'Maison',
    typeLabel: 'Maison',
    status: 'À vendre',
    city: 'Évian-les-Bains',
    cp: '74500',
    price: 590000,
    surface: 74.26,
    land: 660,
    rooms: 3,
    bedrooms: 2,
    baths: null,
    dpe: 'F',
    ges: 'F',
    coupDeCoeur: false,
    highlights: ['Terrain viabilisé', 'Vue lac léman', 'Quartier calme résidentiel'],
    description: 'Mickaël Lima de L\'agence Immo est ravie de vous présenter ce chalet de 74 m² habitables implanté sur un terrain de 660 m², situé à Évian-les-Bains, offrant une vue sur le lac et un fort potentiel, aussi bien pour un projet de rénovation que pour une construction neuve.\n\nAménagement intérieur :\n\nCe chalet, construit en 1964 et réparti sur deux niveaux, propose une base existante à rénover selon vos envies. Son état général nécessite des travaux de rafraîchissement, laissant la possibilité de repenser entièrement les espaces pour créer un lieu de vie moderne et confortable. Une cave vient compléter le bien, offrant un espace de stockage supplémentaire.\n\nAménagement extérieur :\n\nLe terrain de 560 m² permet d’envisager un projet global, que ce soit dans le cadre d’une rénovation ou d’une démolition suivie d’une construction neuve. Situé en zone UP du PLU, ce bien offre une emprise au sol d’environ 180 m², permettant la réalisation d’une maison spacieuse. Les règles d’urbanisme imposent un recul minimum de 6 mètres par rapport à la voirie et aux limites séparatives, garantissant un cadre aéré et résidentiel. Une grande partie du terrain devra être conservée en espaces verts, assurant un environnement agréable et paysager.\n\nPrestations et équipements :\n\nLe bien est raccordé aux réseaux d’eau, d’électricité, d’assainissement ainsi qu’aux télécommunications. Le chauffage actuel est individuel au fioul avec production d’eau chaude électrique. L’exposition plein sud et la vue sur le lac constituent de véritables atouts pour valoriser un futur projet.\n\nLocalisation et commodités :\n\nIdéalement situé sur les hauteurs d’Évian-les-Bains, ce bien bénéficie d’un emplacement privilégié avec une vue dégagée sur le lac Léman, offrant un cadre de vie rare et recherché. Vous profitez d’un environnement calme et résidentiel tout en restant à proximité du centre-ville, de ses commerces, écoles et infrastructures. La situation permet également un accès rapide vers la Suisse, notamment Lausanne via les liaisons lacustres.\n\nInformations complémentaires :\n\nCe bien offre une double opportunité : rénover le chalet existant ou envisager un nouveau projet de construction, avec un potentiel de développement important selon les règles du PLU en zone UP. Disponible immédiatement, il constitue une opportunité rare sur le secteur.',
    features: [
      ['Surface', '74.26 m²'],
      ['Pièces', '3'],
      ['Terrain', '660 m²'],
      ['Niveaux (RDC inclus)', '2'],
      ['Chambres', '2'],
      ['Cuisine', 'Non équipée/Coin cuisine'],
      ['Exposition', 'Sud']
    ],
    photos: [
      '/images/biens/VM1022/01.jpg',
      '/images/biens/VM1022/02.jpg',
      '/images/biens/VM1022/03.jpg',
      '/images/biens/VM1022/04.jpg',
      '/images/biens/VM1022/05.jpg'
    ],
  },
  {
    ref: 'VM1063',
    slug: 'maison-mitoyenne-1-cote-5-pieces-peron-01630',
    title: 'Maison de ville de 128 m² avec terrasse de 70 m² sans vis-à-vis, jardin et garage : Péron 01630',
    type: 'Maison',
    typeLabel: 'Maison Mitoyenne 1 côté',
    status: 'À vendre',
    city: 'Péron',
    cp: '01630',
    price: 575000,
    surface: 121,
    land: 270,
    rooms: 5,
    bedrooms: 3,
    baths: 2,
    dpe: 'D',
    ges: 'B',
    coupDeCoeur: true,
    highlights: ['Maison rénovée avec gout', 'Jardin sans vis à vis', 'Places de stationnements'],
    description: 'Située dans le hameau de Péron, cette maison bénéficie d\'un environnement calme tout en restant proche des écoles, commerces, services et infrastructures sportives. Les frontaliers rejoignent rapidement Saint-Genis-Pouilly, le CERN, Meyrin et Genève. Les amoureux de nature apprécieront les nombreux sentiers de randonnée, les itinéraires VTT et les panoramas du massif du Jura.\n\nInformations complémentaires :\n\nDPE : D (184 kWhEP/m².an) - GES : B (7 kg CO₂/m².an).\n\nMontant estimé des dépenses annuelles d\'énergie : entre 2 074 € et 2 806 €.',
    features: [
      ['Surface', '121 m²'],
      ['Pièces', '5'],
      ['Salle de bains', '1'],
      ['Terrain', '270 m²'],
      ['Salle d\'eau', '1'],
      ['Niveaux (RDC inclus)', '3'],
      ['Chambres', '3'],
      ['WC', '3'],
      ['Piscine', 'Non'],
      ['Stationnement intérieur', '2'],
      ['Stationnement extérieur', '2'],
      ['Cuisine', 'Aménagée et équipée/Coin cuisine'],
      ['Exposition', 'Est'],
      ['Jardin', 'Oui']
    ],
    photos: [
      '/images/biens/VM1063/01.jpg',
      '/images/biens/VM1063/02.jpg',
      '/images/biens/VM1063/03.jpg',
      '/images/biens/VM1063/04.jpg',
      '/images/biens/VM1063/05.jpg',
      '/images/biens/VM1063/06.jpg',
      '/images/biens/VM1063/07.jpg',
      '/images/biens/VM1063/08.jpg',
      '/images/biens/VM1063/09.jpg',
      '/images/biens/VM1063/10.jpg',
      '/images/biens/VM1063/11.jpg',
      '/images/biens/VM1063/12.jpg'
    ],
  },
  {
    ref: 'VT095',
    slug: 'terrain-constructible-570-m2-evian-les-bains-74500',
    title: 'Terrain constructible 570 m² avec vue lac : Évian-les-Bains (74500) : Emprise 160 m²',
    type: 'Terrain',
    typeLabel: 'Terrain',
    status: 'À vendre',
    city: 'Évian-les-Bains',
    cp: '74500',
    price: 435000,
    surface: null,
    land: 570,
    rooms: null,
    bedrooms: null,
    baths: null,
    dpe: null,
    ges: null,
    coupDeCoeur: false,
    highlights: ['Vue lac Léman', 'Terrain viabilisé', 'Quartier résidentiel calme'],
    description: 'Mickaël Lima est ravie de vous présenter ce terrain constructible de 570 m², idéalement situé à Évian-les-Bains, offrant une agréable vue sur le lac et un fort potentiel de construction dans un environnement résidentiel recherché.\n\nAménagement intérieur :\n\nCe terrain situé en zone UP du PLU permet la réalisation d’une maison individuelle parfaitement intégrée à son environnement. L’emprise au sol maximale autorisée est d’environ 160 m², offrant la possibilité de concevoir un projet spacieux et confortable. La hauteur maximale autorisée est de 7 mètres à l’égout du toit et peut atteindre 10 mètres au point le plus haut en cas de toit habitable. Le règlement autorise jusqu’à 3 logements maximum sur l’unité foncière, tout en préservant le caractère pavillonnaire du secteur.\n\nAménagement extérieur :\n\nLe terrain, piscinable, permet d’imaginer de beaux aménagements extérieurs dans un cadre privilégié avec vue sur le lac. Les constructions devront respecter un recul minimum de 6 mètres par rapport à l’alignement existant ou à créer ainsi que par rapport aux limites séparatives. Les piscines devront être implantées à 5 mètres minimum de l’alignement et à 4 mètres minimum des limites séparatives. Les espaces non bâtis devront être aménagés en espaces verts ou paysagers sur au moins 65 % de la surface totale du terrain, garantissant un cadre de vie verdoyant et harmonieux.\n\nPrestations et équipements :\n\nLe terrain est viabilisé et bénéficie des raccordements à l’eau, à l’électricité, au gaz, aux télécommunications ainsi qu’à l’assainissement, facilitant la mise en œuvre de votre projet. Il dispose également d’une servitude de passage par une voie privée existante. Le stationnement devra être prévu conformément aux règles en vigueur, avec un minimum de deux places par logement créé.\n\nLocalisation et commodités :\n\nIdéalement situé sur les hauteurs d’Évian-les-Bains, ce terrain bénéficie d’un emplacement privilégié offrant une vue dégagée sur le lac Léman, véritable atout rare sur le secteur. Ce cadre exceptionnel permet de profiter pleinement d’un environnement paisible et verdoyant, tout en étant à proximité immédiate du centre-ville, de ses commerces, restaurants et infrastructures.\n\nLa situation géographique permet également de rejoindre rapidement les axes principaux ainsi que la Suisse, notamment Lausanne via les liaisons lacustres, faisant de ce bien un emplacement recherché tant pour une résidence principale que secondaire.\n\nInformations complémentaires :\n\nCe terrain constructible de 570 m² est disponible immédiatement et constitue une opportunité rare pour un projet de construction dans un secteur prisé d’Évian-les-Bains. Mickael Lima de L’Agence Immo, expert immobilier sur le Pays de Gex et la Haute-Savoie, vous présente ce bien et se tient à votre disposition pour vous accompagner dans la découverte de ce terrain ainsi que dans l’étude de votre projet.',
    features: [
      ['Terrain', '570 m²'],
      ['Electricité', 'Oui']
    ],
    photos: [
      '/images/biens/VT095/01.jpg',
      '/images/biens/VT095/02.jpg',
      '/images/biens/VT095/03.jpg',
      '/images/biens/VT095/04.jpg',
      '/images/biens/VT095/05.jpg'
    ],
  },
  {
    ref: 'VT093',
    slug: 'terrain-constructible-530-m2-evian-les-bains-74500',
    title: 'Terrain constructible 530 m² avec vue lac Léman : Évian-les-Bains (74500) : Emprise 148 m² : Secteur recherché',
    type: 'Terrain',
    typeLabel: 'Terrain',
    status: 'À vendre',
    city: 'Évian-les-Bains',
    cp: '74500',
    price: 415000,
    surface: null,
    land: 530,
    rooms: null,
    bedrooms: null,
    baths: null,
    dpe: null,
    ges: null,
    coupDeCoeur: false,
    highlights: ['Vue lac léman', 'Quartier calme résidentiel', 'Terrain viabilisé'],
    description: 'Mickael Lima, spécialiste immobilier est ravie de vous présenter ce superbe terrain constructible de 530 m², idéalement situé à Évian-les-Bains (74500), offrant une belle vue sur le lac. Ce terrain constitue une belle opportunité pour la réalisation d’une maison individuelle dans un environnement résidentiel recherché.\n\nConstruction et Aménagement :\n\nSur ce terrain de 530 m² situé en zone UP du PLU, l’emprise au sol maximale autorisée est d’environ 148 m², conformément au coefficient applicable de 0,28 pour cette tranche de surface. La hauteur maximale autorisée est de 7 m à l’égout du toit, et peut atteindre 10 m au point le plus haut en cas de toit habitable.\n\nImplantation et Limites :\n\nLes constructions doivent être implantées avec un recul minimum de 6 m par rapport à l’alignement existant ou à créer, ainsi que par rapport aux voies privées ouvertes à la circulation publique. Elles doivent également respecter un retrait minimum de 6 m par rapport aux limites séparatives. Les piscines doivent être implantées à 5 m minimum de l’alignement et à 4 m minimum des limites séparatives.\n\nAménagement Paysager :\n\nLes espaces non bâtis doivent être traités en espaces verts ou paysagers sur au moins 65 % de la surface totale du terrain, dont la moitié minimum en pleine terre. Pour ce terrain, cela représente environ 344 m² d’espaces verts, dont environ 172 m² en pleine terre. Le règlement impose également la plantation d’au minimum 3 arbres sur la parcelle. Le terrain étant piscinable, il offre de belles possibilités d’aménagement extérieur dans un cadre agréable et valorisant.\n\nInformations Complémentaires :\n\nLe terrain est situé en zone résidentielle de faible densité, destinée à préserver le caractère pavillonnaire du secteur. Il bénéficie d’une servitude de passage par voie privée existante et est disponible immédiatement. Les raccordements à l’eau, à l’électricité, au gaz, aux télécommunications ainsi que l’assainissement sont déjà en place, facilitant la réalisation de votre projet.',
    features: [
      ['Terrain', '530 m²'],
      ['Constructible', '250 m²'],
      ['Electricité', 'Oui']
    ],
    photos: [
      '/images/biens/VT093/01.jpg',
      '/images/biens/VT093/02.jpg',
      '/images/biens/VT093/03.jpg',
      '/images/biens/VT093/04.jpg',
      '/images/biens/VT093/05.jpg'
    ],
  },
  {
    ref: 'VA2352',
    slug: 'appartement-t4-4-pieces-ferney-voltaire-01210-va2352',
    title: 'Appartement t4 : cuisine indépendante : cave : parking : centre-ville : Ferney-Voltaire 01210',
    type: 'Appartement',
    typeLabel: 'Appartement',
    status: 'À vendre',
    city: 'Ferney-Voltaire',
    cp: '01210',
    price: 370000,
    surface: 85.17,
    land: null,
    rooms: 4,
    bedrooms: 2,
    baths: 1,
    dpe: 'C',
    ges: 'C',
    coupDeCoeur: false,
    highlights: ['Résidence rénovée récemment', 'Séjour donnant sur espaces verts', 'Emplacement idéale'],
    description: 'Mickaël Lima, spécialiste immobilier sur le secteur du Pays de Gex et alentours, est ravi de vous présenter ce T4 de 85,17 m² habitables, situé au 6ᵉ étage d’une résidence rénovée récemment en plein cœur de Ferney-Voltaire. L’appartement dispose de deux chambres, d’un salon lumineux, d’une salle à manger accueillante, d’une cuisine indépendante aménagée et équipée, d’une salle d’eau moderne et d’un WC séparé. Une cave ainsi qu’une place de parking extérieure viennent compléter ce bien.\n\nAménagement intérieur :\n\nL’entrée dessert un couloir fonctionnel qui mène à un agréable salon baigné de lumière naturelle, parfait pour vos instants de détente, à une salle à manger spacieuse idéale pour recevoir, mais aussi à une cuisine indépendante aménagée et équipée, bien pensée pour le quotidien. Côté nuit, deux chambres confortables offrent calme et intimité. Une salle d’eau et un WC indépendant viennent compléter cet ensemble harmonieux. Le bien comprend également une cave, offrant une solution de rangement supplémentaire très appréciée.\n\nAménagement extérieur :\n\nSitué au 6ème étage dans un immeuble de huit niveaux avec ascenseur, l’appartement bénéficie d’une vue entièrement dégagée sur les montagnes. L’environnement immédiat est agréable et verdoyant, avec des espaces extérieurs communs bien entretenus.\n\nPrestations et équipements :\n\nCe bien est situé dans une copropriété ayant récemment bénéficié de travaux d’entretien majeurs : isolation extérieure des façades, isolation des toitures et des plafonds des caves, rénovation des parties communes, et remplacement de l’ancien système de chauffage au fioul par un chauffage collectif au gaz plus performant et économique.\n\nL’appartement bénéficie de menuiseries aluminium à double vitrage neuves, assurant confort thermique et phonique. Le chauffage collectif au sol garantit une température homogène dans toutes les pièces.\n\nL’immeuble est équipé d’un ascenseur. Une place de stationnement extérieure non couverte est incluse avec le logement. Une cave privative est également rattachée à l’appartement, idéale pour optimiser vos rangements.\n\nLocalisation et commodités :\n\nSitué en plein centre-ville de Ferney-Voltaire, ce bien vous place à proximité immédiate des commerces, restaurants, écoles, du marché hebdomadaire, de la Cité Scolaire Internationale, ainsi que de l’aéroport de Genève.\n\nLes transports en commun desservent efficacement la commune grâce aux lignes TPG suivantes :\n\nLigne 60 : Gex L’Aiglette ↔ Genève Gare Cornavin\n\nLigne 61 : Saint-Genis-Pouilly ↔ Genève Cornavin (via Ferney-Voltaire)\n\nLigne 66 : Thoiry Centre Commercial ↔ Genève Aéroport Terminal\n\nÀ l’horizon fin 2028, l’attractivité du quartier sera encore renforcée avec l’arrivée d’une nouvelle ligne de tramway qui reliera le P+R du Bijou à Ferney-Voltaire au quartier des Nations à Genève, facilitant encore davantage l’accès au centre-ville genevois.\n\nInformations complémentaires :\n\nCharges de copropriété : 257 €/mois, comprenant l’eau chaude, le chauffage, l’entretien des parties communes, des espaces verts et le ramassage des ordures ménagères.\n\nCopropriété bien entretenue de 214 lots, dont 82 logements. Syndic professionnel : ORKAN MANAGEMENT.',
    features: [
      ['Surface', '85.17 m²'],
      ['Pièces', '4'],
      ['Salle d\'eau', '1'],
      ['Chambres', '2'],
      ['WC', '1'],
      ['Piscine', 'Non'],
      ['Stationnement extérieur', '1'],
      ['Cuisine', 'Aménagée et équipée/Indépendante'],
      ['Jardin', 'Non']
    ],
    photos: [
      '/images/biens/VA2352/01.jpg',
      '/images/biens/VA2352/02.jpg',
      '/images/biens/VA2352/03.jpg',
      '/images/biens/VA2352/04.jpg',
      '/images/biens/VA2352/05.jpg',
      '/images/biens/VA2352/06.jpg',
      '/images/biens/VA2352/07.jpg',
      '/images/biens/VA2352/08.jpg'
    ],
  },
  {
    ref: 'VA2539',
    slug: 'appartement-t4-4-pieces-ferney-voltaire-01210-va2539',
    title: 'EXCLUSIVITÉ - APPARTEMENT T4 AVEC VUES SALÈVE ET JURA - FERNEY-VOLTAIRE',
    type: 'Appartement',
    typeLabel: 'Appartement',
    status: 'À vendre',
    city: 'Ferney-Voltaire',
    cp: '01210',
    price: 370000,
    surface: 87,
    land: null,
    rooms: 4,
    bedrooms: 3,
    baths: 2,
    dpe: 'D',
    ges: 'D',
    coupDeCoeur: false,
    highlights: ['Emplacement idéal en plein centre ville', 'Proche des écoles', 'Appartement bien aménagé', 'Avant dernier étage de l\'immeuble'],
    description: 'Situé dans une résidence bénéficiant d\'espaces communs entretenus, le bien dispose d\'une place de stationnement extérieure privative facilitant le quotidien. Une cave complète également les prestations et offre un espace de stockage particulièrement appréciable.\n\nSa situation en étage élevé permet de profiter d\'un cadre de vie agréable avec des vues dégagées sur les massifs environnants, véritable atout pour ce secteur recherché de Ferney-Voltaire.\n\nPrestations et équipements :\n\nConstruit en 1975 au sein d\'une copropriété sécurisée, l\'appartement bénéficie d\'un chauffage collectif au gaz ainsi que d\'une production d\'eau chaude collective. Les équipements présents contribuent au confort quotidien avec un digicode, la fibre optique et un local à vélos accessible aux résidents.\n\nLes menuiseries en aluminium et la ventilation par VMI participent au bon fonctionnement général du logement. Quelques travaux de modernisation permettront d\'exploiter pleinement le potentiel de ce bien aux volumes particulièrement intéressants.\n\nLocalisation et commodités :\n\nSitué à Ferney-Voltaire, cet appartement bénéficie d\'un emplacement particulièrement recherché à proximité immédiate de la frontière suisse, de l\'aéroport international de Genève, des organisations internationales et des principaux bassins d\'emploi de la région.\n\nLes commerces, établissements scolaires, transports en commun et services du quotidien sont accessibles rapidement, offrant un cadre de vie pratique et recherché. Cette localisation constitue un véritable atout pour les familles comme pour les actifs travaillant en Suisse.\n\nInformations complémentaires :\n\nAucune procédure en cours contre la copropriété ou le syndic.\n\nCharges de copropriété : environ 441 € par mois, comprenant le chauffage collectif, l\'eau froide, l\'entretien des parties communes, l\'ascenseur, les espaces verts, l\'entretien des équipements communs ainsi que les honoraires du syndic.\n\nMontant estimé des dépenses annuelles d\'énergie pour un usage standard : entre 1 093 € et 1 479 € par an.',
    features: [
      ['Surface', '87 m²'],
      ['Pièces', '4'],
      ['Salle de bains', '1'],
      ['Salle d\'eau', '1'],
      ['Chambres', '3'],
      ['WC', '1'],
      ['Stationnement extérieur', '1'],
      ['Cuisine', 'Aménagée et équipée/Indépendante'],
      ['Exposition', 'Sud-Ouest'],
      ['Jardin', 'Non']
    ],
    photos: [
      '/images/biens/VA2539/01.jpg',
      '/images/biens/VA2539/02.jpg',
      '/images/biens/VA2539/03.jpg',
      '/images/biens/VA2539/04.jpg',
      '/images/biens/VA2539/05.jpg',
      '/images/biens/VA2539/06.jpg',
      '/images/biens/VA2539/07.jpg',
      '/images/biens/VA2539/08.jpg',
      '/images/biens/VA2539/09.jpg',
      '/images/biens/VA2539/10.jpg',
      '/images/biens/VA2539/11.jpg'
    ],
  },
  {
    ref: 'VM835',
    slug: 'maison-individuelle-7-pieces-vetraz-monthoux-74100',
    title: 'Sous compromis',
    type: 'Maison',
    typeLabel: 'Maison Individuelle',
    status: 'Sous compromis',
    city: 'Vétraz-Monthoux',
    cp: '74100',
    price: null,
    surface: 283.53,
    land: 997,
    rooms: 7,
    bedrooms: 5,
    baths: 2,
    dpe: null,
    ges: null,
    coupDeCoeur: false,
    highlights: ['Idéalement situé', 'Gros potentiel', 'Espaces extérieurs'],
    description: 'Mickaël Lima, expert immobilier sur le secteur de la Haute‑Savoie, du Pays de Gex et de leurs environs, est ravi de vous présenter cette spacieuse maison familiale située à Vétraz-Monthoux, au cœur d’un quartier résidentiel calme et recherché, à seulement quelques minutes d’Annemasse et des accès rapides vers Genève.\n\nÉdifiée sur une belle parcelle de 997 m², cette maison individuelle développe 283 m² habitables pour une surface totale au sol de 336 m², répartis sur trois niveaux. Elle séduit par ses volumes généreux, son agencement fonctionnel et son potentiel rare de division en plusieurs logements indépendants.\n\nAvec ses 5 chambres, deux salons, deux salles de bains, un vaste sous-sol aménagé, un garage double et plusieurs terrasses, elle s’adapte parfaitement aux besoins d’une grande famille, d’un projet multi-générationnel ou d’un investissement locatif stratégique.\n\nAménagement intérieur :\n\nLe rez-de-chaussée s’ouvre sur un vaste séjour de 45 m² baigné de lumière, prolongé par une cuisine indépendante équipée. Trois chambres y sont réparties, ainsi qu’une salle de bains et un WC indépendant.\n\nÀ l’étage, vous découvrirez un second espace salon de 28 m², deux chambres supplémentaires, une salle d’eau et un second WC, le tout structuré autour d’un large dégagement.\n\nLe sous-sol, accessible depuis l’extérieur, offre près de 80 m² supplémentaires dont une partie est déjà aménagée, comprenant une vaste pièce de vie, un couloir d’entrée et divers espaces de rangement.\n\nAménagement extérieur :\n\nLa maison est implantée sur une belle parcelle arborée de 997 m², offrant un cadre de vie paisible et agréable. Le jardin exposé plein sud prolonge harmonieusement les espaces de vie et invite à la détente comme aux repas en extérieur. Le jardin, soigneusement entretenu, accueille également un potager aménagé, idéal pour cultiver vos propres fruits et légumes.\n\nAu rez-de-chaussée, un balcon accessible depuis le séjour et l’une des chambres permet de profiter d’une vue dégagée sur la cour, tout en offrant une agréable continuité entre intérieur et extérieur.\n\nCôté stationnement, la propriété dispose d’un garage double  et permet de garer facilement plusieurs véhicules sur la parcelle, un véritable atout pour les grandes familles ou les réceptions.\n\nPrestations et équipements :\n\nConstruite en 1986, cette maison présente une structure saine, mais nécessite des travaux de rafraîchissement généralainsi que des interventions ponctuelles au niveau de l’installation électrique, notamment dans certaines pièces.\n\nElle dispose d’un chauffage électrique individuel, d’une VMC simple flux, de menuiseries bois avec double vitrage et d’une cuisine indépendante équipée..\n\nLa configuration intérieure permet une grande souplesse d’aménagement, idéale pour un projet de division ou une occupation multi-générationnelle.\n\nLocalisation et commodités :\n\nIdéalement située à Vétraz-Monthoux, la maison bénéficie d’un cadre de vie résidentiel très recherché, tout en restant proche des commodités : écoles (de la maternelle au secondaire), commerces, établissements de santé et équipements sportifs sont accessibles en quelques minutes.\n\nCôté transports, la commune est desservie par le réseau TAC :\n\nLa ligne 8 relie Vétraz-Monthoux à la gare d’Annemasse, facilitant l’accès aux correspondances vers Genève.\n\nLa ligne 7, quant à elle, permet de rejoindre Cranves-Sales Altéa P+R, avec un arrêt situé au P+R Jean Monnet à Vétraz-Monthoux, pratique pour les trajets en direction de la frontière tout en stationnant facilement son véhicule.\n\nCes dessertes offrent une véritable alternative à la voiture pour les déplacements quotidiens, notamment pour les actifs transfrontaliers.\n\nInformations complémentaires :\n\nLe bien est libre de toute occupation et disponible immédiatement, prêt à accueillir vos projets de vie ou d’investissement.\n\nGrâce à sa configuration intérieure généreuse et bien pensée, la maison se prête aisément à une division partielle ou totale en plusieurs logements avec accès indépendant: une opportunité rare pour les investisseurs ou les familles souhaitant regrouper plusieurs générations sous un même toit.\n\nPour plus d’informations sur les risques éventuels auxquels ce bien est exposé, consultez le site officiel : www.georisques.gouv.fr.',
    features: [
      ['Surface', '283.53 m²'],
      ['Pièces', '7'],
      ['Salle de bains', '1'],
      ['Terrain', '997 m²'],
      ['Salle d\'eau', '1'],
      ['Séjour', '45 m²'],
      ['Niveaux (RDC inclus)', '3'],
      ['Chambres', '5'],
      ['WC', '2'],
      ['Piscine', 'Non'],
      ['Stationnement intérieur', '2'],
      ['Stationnement extérieur', '6'],
      ['Cuisine', 'Equipée/Indépendante'],
      ['Exposition', 'Sud'],
      ['Jardin', 'Oui']
    ],
    photos: [
      '/images/biens/VM835/01.jpg',
      '/images/biens/VM835/02.jpg',
      '/images/biens/VM835/03.jpg',
      '/images/biens/VM835/04.jpg',
      '/images/biens/VM835/05.jpg',
      '/images/biens/VM835/06.jpg',
      '/images/biens/VM835/07.jpg',
      '/images/biens/VM835/08.jpg',
      '/images/biens/VM835/09.jpg',
      '/images/biens/VM835/10.jpg',
      '/images/biens/VM835/11.jpg',
      '/images/biens/VM835/12.jpg'
    ],
  },
  {
    ref: 'VA2424',
    slug: 'appartement-t3-3-pieces-cessy-01170',
    title: 'Appartement T3 60 m² : Jardin Privatif : 2 Parkings En Sous-Sol : Cave : Résidence Récente : Cessy 01170',
    type: 'Appartement',
    typeLabel: 'Appartement',
    status: 'Vendu',
    city: 'Cessy',
    cp: '01170',
    price: null,
    surface: 60,
    land: null,
    rooms: 3,
    bedrooms: 2,
    baths: 1,
    dpe: null,
    ges: null,
    coupDeCoeur: false,
    highlights: ['Places de parkings en sous sol', 'Jardin privatif', 'Proche centre ville de cessy'],
    description: 'Mickaël Lima, expert immobilier sur le Pays de Gex et alentours, est heureux de vous présenter cet agréable appartement 3 pièces en rez-de-jardin, situé dans une résidence récente et bien entretenue, à Cessy, à proximité immédiate de Saint‑Genis‑Pouilly et de la frontière suisse. Avec ses deux chambres, son jardin privatif, sa cave et ses deux places de stationnement en sous-sol, ce bien constitue une belle opportunité pour un cadre de vie confortable et fonctionnel dans un environnement paisible.\n\nAménagement intérieur :\n\nD’une surface habitable d’environ 60 m², l’appartement s’ouvre sur une entrée avec rangements, desservant une salle de bains et un WC indépendant. La partie nuit se compose de deux chambres confortables. La pièce de vie principale réunit un séjour convivial et une cuisine aménagée et équipée ouverte, offrant un espace pratique pour le quotidien. Une cave vient compléter l’ensemble, ainsi que deux places de stationnement privatives situées en sous-sol.\n\nAménagement extérieur :\n\nAccessible directement depuis le séjour, le jardin privatif prolonge l’espace de vie vers l’extérieur et offre un cadre idéal pour profiter des beaux jours. Ce jardin s’ouvre sur une cour intérieure paysagée partagée par les résidents, soigneusement entretenue, renforçant l’ambiance agréable et résidentielle de la copropriété.\n\nPrestations et équipements :\n\nL’appartement est équipé d’un chauffage individuel au gaz avec chauffe‑eau intégré, de menuiseries PVC double vitrage, et d’un système de ventilation VMC simple flux. Deux places de stationnement privatives en sous-sol sont incluses, offrant confort et sécurité au quotidien. Une cave privative vient également compléter les prestations. La résidence, construite en 2019, est pourvue d’un ascenseur et présente un bon état général, tant à l’intérieur que dans les parties communes.\n\nLocalisation et commodités :\n\nIdéalement situé à Cessy, à seulement quelques minutes de Saint‑Genis‑Pouilly, ce bien bénéficie d’un accès rapide aux commerces, à la zone de Val‑Thoiry, au centre culturel Jean Monnet ainsi qu’aux services communaux (mairie, poste, équipements sportifs et associatifs).\n\nLa commune est desservie par les lignes TPG 60 et 61, reliant notamment Gex ↔ Cessy ↔ Ferney-Voltaire ↔ Genève (gare Cornavin), avec des arrêts à Cessy Centre, Côte du Moralay et Les Hauts de Cessy, permettant de rejoindre facilement la Suisse et les communes du Pays de Gex.\n\nCôté scolarité, vous trouverez à proximité immédiate l’école primaire de Cessy, les écoles maternelle et élémentaire de Saint‑Genis‑Pouilly, le collège Jacques Prévert, ainsi que l’école internationale de Ferney‑Voltaire (site Saint‑Genis).\n\nInformations complémentaires :\n\nLes charges de copropriété s’élèvent à 340 € par trimestre, comprenant l’eau froide, l’entretien de l’immeuble et des espaces verts.',
    features: [
      ['Surface', '60 m²'],
      ['Pièces', '3'],
      ['Salle de bains', '1'],
      ['Ascenseur', 'Oui'],
      ['Chambres', '2'],
      ['WC', '1'],
      ['Piscine', 'Non'],
      ['Stationnement intérieur', '2'],
      ['Cuisine', 'Aménagée et équipée/Coin cuisine'],
      ['Exposition', 'Sud-Ouest'],
      ['Jardin', 'Oui']
    ],
    photos: [
      '/images/biens/VA2424/01.jpg',
      '/images/biens/VA2424/02.jpg',
      '/images/biens/VA2424/03.jpg',
      '/images/biens/VA2424/04.jpg',
      '/images/biens/VA2424/05.jpg',
      '/images/biens/VA2424/06.jpg',
      '/images/biens/VA2424/07.jpg',
      '/images/biens/VA2424/08.jpg',
      '/images/biens/VA2424/09.jpg',
      '/images/biens/VA2424/10.jpg'
    ],
  },
  {
    ref: 'VM760',
    slug: 'maison-individuelle-7-pieces-cessy-01170',
    title: 'Villa individuelle 4 chambres à Cessy avec piscine, jardin et terrasse',
    type: 'Maison',
    typeLabel: 'Maison Individuelle',
    status: 'Vendu',
    city: 'Cessy',
    cp: '01170',
    price: null,
    surface: 241.34,
    land: 1221,
    rooms: 7,
    bedrooms: 4,
    baths: 3,
    dpe: null,
    ges: null,
    coupDeCoeur: false,
    highlights: ['Environnement calme et verdoyant', 'Sans vis à vis', 'Isolation performante', 'Grandes baies vitrées'],
    description: 'Mickaël Lima expert immobilier sur le secteur du Pays de Gex et ses alentours, est ravi de vous présenter cette élégante villa individuelle de 241 m² habitables, comprenant 7 pièces dont 4 chambres, implantée sur un terrain paysager de 1 221 m². Avec son vaste séjour lumineux, son jardin clos, sa piscine chauffée et son atelier indépendant, elle constitue un véritable havre de paix pour une vie familiale confortable à Cessy.\n\nAménagement intérieur :\n\nDès l’entrée, vous serez séduit par un vaste séjour et salle à manger lumineux, sublimé par une cheminée fonctionnelle et de larges baies vitrées en bois double vitrage ouvrant directement sur le jardin. La cuisine, entièrement aménagée et équipée, se révèle aussi conviviale que pratique.\n\nLe rez-de-chaussée accueille également une salle de jeu avec billard et sauna, ainsi qu’une buanderie fonctionnelle. Une chambre et une salle d’eau avec WC complètent ce niveau.\n\nÀ l’étage, la suite parentale bénéficie d’un balcon avec vue dégagée sur la chaîne des Alpes, d’une salle de bain avec douche et WC, ainsi que d’un dressing indépendant. Deux chambres supplémentaires et une salle de bains avec WC viennent parfaire l’espace nuit, offrant des volumes généreux pour enfants, invités ou bureau.\n\nAménagement extérieur :\n\nLe jardin clos et parfaitement entretenu profite d’un système d’arrosage automatique. La terrasse exposée sud-ouest se prolonge sur une piscine chauffée par pompe à chaleur, un jacuzzi, un barbecue intégré et un pool house au style exotique. En annexe, un atelier indépendant avec abri offre de nombreux espaces de rangement. Côté stationnement, un carport accueille deux véhicules et au moins trois autres places sont disponibles à l’avant.\n\nPrestations et équipements :\n\nConstruite en 2007, cette villa conjugue confort et modernité. Elle dispose d’un chauffage individuel au gaz, de volets électriques, d’un système d’alarme, d’un visiophone et d’un portail motorisé. Les menuiseries en bois double vitrage participent à la luminosité intérieure et au confort thermique.\n\nLocalisation et commodités :\n\nNichée dans un quartier résidentiel calme et verdoyant de Cessy, la villa se situe à proximité immédiate des établissements scolaires, des commerces et du centre-ville de Gex. Vous profiterez également des équipements de loisirs tels qu’un centre équestre, une piscine municipale, un gymnase et la voie verte pour vos promenades.\n\nCôté transports, la ligne de bus TPG F dessert la liaison Ferney-Voltaire ↔ Genève Gare Cornavin, facilitant vos déplacements vers Genève et son agglomération.\n\nInformations complémentaires :\n\nLa maison, située dans un lotissement calme est disponible immédiatement. Les charges annuelles de l’ASL s’élèvent à environ 100 €, couvrant l’entretien des voiries et l’électricité des équipements collectifs de la rue. De plus, un entretien complet ainsi qu’un ponçage intégral du bois ont été réalisés il y a environ deux ans, garantissant un état impeccable de la villa."',
    features: [
      ['Surface', '241.34 m²'],
      ['Pièces', '7'],
      ['Salle de bains', '2'],
      ['Terrain', '1 221 m²'],
      ['Salle d\'eau', '1'],
      ['Niveaux (RDC inclus)', '2'],
      ['Chambres', '4'],
      ['WC', '3'],
      ['Piscine', 'Oui'],
      ['Stationnement intérieur', '2'],
      ['Stationnement extérieur', '3'],
      ['Cuisine', 'Aménagée et équipée/Coin cuisine'],
      ['Exposition', 'Sud-Ouest'],
      ['Jardin', 'Oui']
    ],
    photos: [
      '/images/biens/VM760/01.jpg',
      '/images/biens/VM760/02.jpg',
      '/images/biens/VM760/03.jpg',
      '/images/biens/VM760/04.jpg',
      '/images/biens/VM760/05.jpg',
      '/images/biens/VM760/06.jpg',
      '/images/biens/VM760/07.jpg',
      '/images/biens/VM760/08.jpg',
      '/images/biens/VM760/09.jpg',
      '/images/biens/VM760/10.jpg',
      '/images/biens/VM760/11.jpg',
      '/images/biens/VM760/12.jpg'
    ],
  },
  {
    ref: 'VM902',
    slug: 'maison-mitoyenne-2-cotes-4-pieces-gex-01170',
    title: 'MAISON DE VILLAGE 133 M² : CENTRE HISTORIQUE : TERRASSE 30 M² : GARAGE : CARACTÈRE AUTHENTIQUE : GEX 01170',
    type: 'Maison',
    typeLabel: 'Maison Mitoyenne 2 côtés',
    status: 'Vendu',
    city: 'Gex',
    cp: '01170',
    price: null,
    surface: 133,
    land: null,
    rooms: 4,
    bedrooms: 3,
    baths: 2,
    dpe: null,
    ges: null,
    coupDeCoeur: false,
    highlights: ['Maison rénovée avec gout', 'Terrasse agréable', 'Nombreux espaces de rangements', 'Maison très bien agencée', 'Chauffage au sol sur les deux niveaux'],
    description: 'Mickaël Lima expert immobilier sur le secteur du Pays de Gex, est fier de vous présenter cette magnifique maison de village, idéalement située au cœur du centre historique de Gex. Rénovée avec soin en 2021, elle développe 106,11 m² en surface loi Carrez et environ 130 m² de surface au sol. Traversante, lumineuse et pleine de caractère, elle invite au voyage dès les premiers pas, grâce à des matériaux nobles, une décoration soignée et une atmosphère chaleureuse et inspirante.\n\nElle propose 3 chambres, une belle terrasse ensoleillée d’environ 30 m², un garage fermé de 18 m² ainsi qu’un sous-sol  d’environ 30 m², offrant un cadre de vie aussi pratique qu’élégant, dans l’un des secteurs les plus recherchés de Gex.\n\nAménagement intérieur :\n\nDès l’entrée, le ton est donné : les sols en béton ciré, présents dans toute la maison, insufflent une cohérence élégante à l’ensemble des espaces. L’agencement traversant, orienté est-ouest, permet à la lumière naturelle d’inonder les pièces de vie tout au long de la journée, tandis que les velux judicieusement positionnés apportent une luminosité optimale jusqu’au dernier niveau.\n\nLe séjour spacieux et convivial s’ouvre directement sur une terrasse de près de 30 m², sans vis-à-vis, exposée ouest. Il communique avec une cuisine équipée semi-ouverte, parfaitement intégrée à l’espace de vie et pensée pour le confort du quotidien. Un WC complète ce niveau.\n\nÀ l’étage, deux chambres composent un espace nuit intime et fonctionnel. La suite parentale dispose d’une salle d’eau privative habillée de carrelage zellige artisanal, apportant une touche authentique et raffinée. Une seconde chambre lumineuse ainsi qu’une vaste salle de bains avec wc décorée de travertin naturel viennent compléter cet étage.\n\nSous les combles aménagés, le dernier niveau accueille un espace modulable comprenant un coin bureau et une chambre indépendante. Lumineux grâce à ses velux et à sa configuration traversante, cet étage constitue un univers à part, parfaitement adapté à un enfant, un adolescent ou un espace de télétravail.\n\nEn complément, la maison dispose d’un sous-sol avec garage fermé de 18 m², facilement accessible depuis l’intérieur, ainsi que de nombreux espaces de rangement intelligemment répartis dans l’ensemble du bien.\n\nAménagement extérieur :\n\nLa terrasse d’environ 30 m², accessible depuis le séjour, constitue un véritable prolongement de la maison. Exposée à l’ouest et située dans un environnement calme, elle devient naturellement le cœur de vos moments de détente et de convivialité, sans les contraintes d’un jardin à entretenir.\n\nPrestations et équipements :\n\nEntièrement rénovée en 2021, cette maison de village conjugue cachet, confort et modernité. Les matériaux choisis : béton ciré, travertin, zellige : offrent une signature esthétique forte, sublimée par une décoration intérieure élégante et cohérente.\n\nLe chauffage au sol, présent sur les deux niveaux principaux, assure une chaleur douce et homogène. L’isolation intérieure est performante, les menuiseries bois/aluminium sont équipées de double vitrage et la maison dispose d’une VMC simple flux.\n\nMitoyenne des deux côtés, elle bénéficie néanmoins d’un environnement calme et d’un excellent état général, sans travaux à prévoir. L’assainissement est collectif et conforme.\n\nLocalisation et commodités :\n\nSituée au cœur du centre historique de Gex, cette maison offre un accès immédiat à pied à l’ensemble des commodités : commerces, restaurants, écoles de la maternelle au lycée, maison médicale, église et Espace Perdtemps.\n\nLes déplacements vers la Suisse sont facilités par les lignes transfrontalières :\n\nLigne 60 TPG : Gex (L’Aiglette / Centre) ↔ Genève (Gare Cornavin)\n\nLigne 61 TPG : Express : Gex (L’Aiglette) ↔ Genève (Gare Cornavin)\n\nLa station de ski Mont Jura : site La Faucille se trouve également à proximité.\n\nInformations complémentaires :\n\nLa maison est disponible immédiatement, sans délai d’emménagement.\n\nElle fait partie d’une copropriété de deux lots d’habitation, sans espaces communs partagés, à l’exception de l’accès technique indépendant à la chaudière, accessible depuis chaque maison.\n\nLes charges de copropriété s’élèvent à 370 € par mois, et comprennent le chauffage, l’eau chaude et l’eau froide.\n\nAucune gestion complexe ou syndic professionnel n’est à prévoir.',
    features: [
      ['Surface', '133 m²'],
      ['Pièces', '4'],
      ['Salle de bains', '1'],
      ['Salle d\'eau', '1'],
      ['Séjour', '27 m²'],
      ['Niveaux (RDC inclus)', '3'],
      ['Chambres', '3'],
      ['WC', '2'],
      ['Piscine', 'Non'],
      ['Stationnement intérieur', '1'],
      ['Cuisine', 'Aménagée et équipée/Coin cuisine'],
      ['Exposition', 'Ouest'],
      ['Jardin', 'Non']
    ],
    photos: [
      '/images/biens/VM902/01.jpg',
      '/images/biens/VM902/02.jpg',
      '/images/biens/VM902/03.jpg',
      '/images/biens/VM902/04.jpg',
      '/images/biens/VM902/05.jpg',
      '/images/biens/VM902/06.jpg',
      '/images/biens/VM902/07.jpg',
      '/images/biens/VM902/08.jpg',
      '/images/biens/VM902/09.jpg',
      '/images/biens/VM902/10.jpg',
      '/images/biens/VM902/11.jpg',
      '/images/biens/VM902/12.jpg'
    ],
  },
];
